### ISSUE TITLE
can't find jbuilder.1.0+beta18

### ISSUE THREAD

**Issue by bcc32** [ocaml/opam-repository#11505] opened 2018-03-01 04:59 UTC
Not sure if this is a problem here or with opam 2 itself, but I don't seem to be able to install (or indeed, find) the latest version of jbuilder.

```
# opam config report
# opam-version      2.0.0~rc
# self-upgrade      no
# system            arch=x86_64 os=macos os-distribution=homebrew os-version=10.13.3
# solver            builtin-mccs+glpk
# install-criteria  -removed,-count[version-lag,request],-count[version-lag,changed],-changed
# upgrade-criteria  -removed,-count[version-lag,solution],-new
# jobs              3
# repositories      1 (http) (default repo at b2ade924)
# pinned            2 (git)
# current-switch    4.05.0
```

```
 ❯ opam show jbuilder

=-=- jbuilder: information on all versions =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=  🐫
name                   jbuilder
all-installed-versions 1.0+beta17 [4.05.0 4.02.3]
all-versions           1.0+beta1  1.0+beta2  1.0+beta3  1.0+beta4  1.0+beta5  1.0+beta6  1.0+beta7  1.0+beta8  1.0+beta9  1.0+beta10  1.0+beta11  1.0+beta12  1.0+beta13
                       1.0+beta14  1.0+beta15  1.0+beta16  1.0+beta17

=-=- Version-specific details -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=  🐫
version       1.0+beta17
repository    default
url.src:      https://github.com/ocaml/dune/releases/download/1.0+beta17/jbuilder-1.0.beta17.tbz

[snip]
```

**Comment by jpdeplaix** [comment] 2018-03-01 10:08
Mmh seems like there are some issues with the bot that is supposed to merge to the 2.0.0 branch automatically.
cc @AltGr

**Comment by AltGr** [comment] 2018-03-01 12:54
Yes, the problem is apparently due to a broken water pipe in Cambridge, causing the power to be down.

**Comment by jpdeplaix** [comment] 2018-03-02 11:54
The water pipe problem is going to be resolve at some point next week but in the meantime @AltGr has kindly setup the Camelus service again on his side.
This should be fixed now.

**Closed by jpdeplaix** 2018-03-02 11:54 UTC

**Comment by AltGr** [comment] 2018-03-02 13:00
Since it seems the repair work will still take some days there, I have put Camelus on a temporary server in the meantime, and replayed the stalled commits. Sorry for the delay!
