### ISSUE TITLE
'opam install ocamlfind' fails on Manjaro with OCaml 4.06.0

### ISSUE THREAD

**Issue by JoanThibault** [ocaml/opam-repository#11453] opened 2018-02-20 12:10 UTC
Hello,
I was trying to 'opam install num' when I got a problem installing ocamlfind.
First I thought it was because of bad interactions between num and ocamlfind, so I erased my .opam hopping it would solve the problem by reinstalling everything in the right way.
Sadly it did not =(
I think the error comes from the module TopLoop :
`# Error: Unbound module Toploop`

I copy-pasted my shell below.
```
[micronova@pascaline DAGaml]$ opam install ocamlfind
The following actions will be performed:
  - install ocamlfind 1.7.3-1

=-=- Gathering sources =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
[ocamlfind] Archive in cache

=-=- Processing actions -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
[ERROR] The compilation of ocamlfind failed at "make all".
Processing  1/1: [ocamlfind: rm]
#=== ERROR while installing ocamlfind.1.7.3-1 =================================#
# opam-version 1.2.2
# os           linux
# command      make all
# path         /home/micronova/.opam/system/build/ocamlfind.1.7.3-1
# compiler     system (4.06.0)
# exit-code    2
# env-file     /home/micronova/.opam/system/build/ocamlfind.1.7.3-1/ocamlfind-12935-d0f245.env
# stdout-file  /home/micronova/.opam/system/build/ocamlfind.1.7.3-1/ocamlfind-12935-d0f245.out
# stderr-file  /home/micronova/.opam/system/build/ocamlfind.1.7.3-1/ocamlfind-12935-d0f245.err
### stdout ###
# ocamlc -I +compiler-libs  -o ocamlfind -g findlib.cma unix.cma \
# [...]
# if [ "false" = "true" ]; then                 \
# 	cp topfind.ml.in topfind.ml;                             \
# else                                                             \
# 	sed -e '/PPXOPT_BEGIN/,/PPXOPT_END/ d' topfind.ml.in     \
# 		> topfind.ml ;                                   \
# fi
# ocamlc -I +compiler-libs -opaque -c topfind.mli
# ocamlc -I +compiler-libs -opaque -g -c topfind.ml
# make[1] : on quitte le répertoire « /home/micronova/.opam/system/build/ocamlfind.1.7.3-1/src/findlib »
### stderr ###
# [...]
# File "frontend.ml", line 2188, characters 25-41:
# Warning 3: deprecated: String.lowercase
# Use String.lowercase_ascii instead.
# File "frontend.ml", line 2193, characters 16-32:
# Warning 3: deprecated: String.lowercase
# Use String.lowercase_ascii instead.
# File "topfind.ml", line 55, characters 12-41:
# Error: Unbound module Toploop
# make[1]: *** [Makefile:168: topfind.cmo] Error 2
# make: *** [Makefile:13: all] Error 2



=-=- Error report -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
The following actions failed
  - install ocamlfind 1.7.3-1
No changes have been performed
[micronova@pascaline DAGaml]$ cd ..
[micronova@pascaline ~]$ rm -rf .opam/
[micronova@pascaline ~]$ opam init
Checking for available remotes: rsync and local, git.
  - you won't be able to use mercurial repositories unless you install the hg command on your system.
  - you won't be able to use darcs repositories unless you install the darcs command on your system.


=-=- Fetching repository information =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
[default] synchronized from https://opam.ocaml.org

=-=- Gathering sources =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

=-=- Processing actions -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
-> installed base-bigarray.base
-> installed base-threads.base
-> installed base-unix.base
Done.

In normal operation, OPAM only alters files within ~/.opam.

During this initialisation, you can allow OPAM to add information to two
other files for best results. You can also make these additions manually
if you wish.

If you agree, OPAM will modify:

  - ~/.bash_profile (or a file you specify) to set the right environment
    variables and to load the auto-completion scripts for your shell (bash)
    on startup. Specifically, it checks for and appends the following line:

    . /home/micronova/.opam/opam-init/init.sh > /dev/null 2> /dev/null || true


  - ~/.ocamlinit to ensure that non-system installations of `ocamlfind`
    (i.e. those installed by OPAM) will work correctly when running the
    OCaml toplevel. It does this by adding $OCAML_TOPLEVEL_PATH to the list
    of include directories.

If you choose to not configure your system now, you can either configure
OPAM manually (instructions will be displayed) or launch the automatic setup
later by running:

   opam config setup -a


Do you want OPAM to modify ~/.bash_profile and ~/.ocamlinit?
(default is 'no', use 'f' to name a file other than ~/.bash_profile)
    [N/y/f] y

User configuration:
  ~/.ocamlinit is already up-to-date.
  ~/.bash_profile is already up-to-date.
Global configuration:
  Updating ~/.opam/opam-init/init.sh
  Updating ~/.opam/opam-init/init.zsh
  Updating ~/.opam/opam-init/init.csh
  Updating ~/.opam/opam-init/init.fish
# To setup the new switch in the current shell, you need to run:
eval `opam config env`
[micronova@pascaline ~]$ opam config env
CAML_LD_LIBRARY_PATH="/home/micronova/.opam/system/lib/stublibs:/usr/lib/ocaml/stublibs"; export CAML_LD_LIBRARY_PATH;
MANPATH="/home/micronova/.opam/system/man:"; export MANPATH;
PERL5LIB="/home/micronova/.opam/system/lib/perl5"; export PERL5LIB;
OCAML_TOPLEVEL_PATH="/home/micronova/.opam/system/lib/toplevel"; export OCAML_TOPLEVEL_PATH;
PATH="/home/micronova/.opam/system/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/var/lib/snapd/snap/bin"; export PATH;
[micronova@pascaline ~]$ opam install ocamlfind
The following actions will be performed:
  - install conf-m4   1                                 [required by ocamlfind]
  - install ocamlfind 1.7.3-1
===== 2 to install =====
Do you want to continue ? [Y/n] y

=-=- Gathering sources =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
[default] https://opam.ocaml.org/archives/ocamlfind.1.7.3-1+opam.tar.gz downloaded

=-=- Processing actions -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
-> installed conf-m4.1
[ERROR] The compilation of ocamlfind failed at "make all".
Processing  2/2: [ocamlfind: rm]
#=== ERROR while installing ocamlfind.1.7.3-1 =================================#
# opam-version 1.2.2
# os           linux
# command      make all
# path         /home/micronova/.opam/system/build/ocamlfind.1.7.3-1
# compiler     system (4.06.0)
# exit-code    2
# env-file     /home/micronova/.opam/system/build/ocamlfind.1.7.3-1/ocamlfind-13773-0a5907.env
# stdout-file  /home/micronova/.opam/system/build/ocamlfind.1.7.3-1/ocamlfind-13773-0a5907.out
# stderr-file  /home/micronova/.opam/system/build/ocamlfind.1.7.3-1/ocamlfind-13773-0a5907.err
### stdout ###
# ocamlc -I +compiler-libs  -o ocamlfind -g findlib.cma unix.cma \
# [...]
# if [ "false" = "true" ]; then                 \
# 	cp topfind.ml.in topfind.ml;                             \
# else                                                             \
# 	sed -e '/PPXOPT_BEGIN/,/PPXOPT_END/ d' topfind.ml.in     \
# 		> topfind.ml ;                                   \
# fi
# ocamlc -I +compiler-libs -opaque -c topfind.mli
# ocamlc -I +compiler-libs -opaque -g -c topfind.ml
# make[1] : on quitte le répertoire « /home/micronova/.opam/system/build/ocamlfind.1.7.3-1/src/findlib »
### stderr ###
# [...]
# File "frontend.ml", line 2188, characters 25-41:
# Warning 3: deprecated: String.lowercase
# Use String.lowercase_ascii instead.
# File "frontend.ml", line 2193, characters 16-32:
# Warning 3: deprecated: String.lowercase
# Use String.lowercase_ascii instead.
# File "topfind.ml", line 55, characters 12-41:
# Error: Unbound module Toploop
# make[1]: *** [Makefile:168: topfind.cmo] Error 2
# make: *** [Makefile:13: all] Error 2



=-=- Error report -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
The following actions failed
  - install ocamlfind 1.7.3-1
The following changes have been performed
  - install conf-m4 1

The former state can be restored with:
    opam switch import "~/.opam/system/backup/state-20180120115956.export"
[micronova@pascaline ~]$ 
```

**Comment by ghasshee** [comment] 2018-03-02 13:47
The same thing happens in Arch Linux.

**Comment by ghasshee** [comment] 2018-03-02 13:48
Why do they change source code without stable versioning ?

**Comment by ghasshee** [comment] 2018-03-02 13:54
I changed my version to `4.06.1`  and then rename it to system with

~~~
opam switch 4.06.1
cd ~/.opam 
rm -rf system
ln -s 4.06.1 system 
~~~

it seems work but ... 
after 4.04.0, I often encounter these nonstable stable version.
I really do not like that.

**Comment by zhxchen17** [comment] 2018-03-17 03:55
The same error produced on my machine as well, using Manjaro.

**Comment by lkwq007** [comment] 2018-03-18 02:58
@zhxchen17 @ghasshee 
I met the same error with the Manjaro 17.1.6. 
But after I installed `ocaml-compiler-libs` `ocaml-findlib` `ocamlbuild` via pacman, `ocamlfind` can be successfully installed. I don't know which package has something to do with this error.

**Comment by kilianbreathnach** [comment] 2018-03-18 21:35
On Arch, I was unable to install any packages using OPAM (pacman version). Once I installed ocaml-findlib with pacman, OPAM seems to work fine, so it seems this is the package which helped. I am completely new with OCaml, however, so I am not sure if there are still some compatibility issues. `opam switch` tells me I am using system compiler 4.06.0

**Comment by hcarty** [comment] 2018-03-19 16:36
Do these issues persist if you use a switch managed by opam rather than a pre-packaged OCaml installation?

**Comment by JoanThibault** [comment] 2018-03-19 19:58
I fully re-installed my machine from scratch with manjaro-xfce-17.1.6-stable-x86_64.iso
The installation of 'ocamlfind' throught 'opam' was still failling =(
However as mentionned above, installing 'ocaml-findlib' with pacman does solve the problem
I think that the build-system of 'ocamlfind' uses to 'ocamlfind' it's dependecies =< .
Here is my log :
```
# setup pacman
sudo pacman-key --init
sudo pacman-mirrors -f0
sudo pacman -S yaourt
yaourt -Syuua
# setup opam
yaourt -S mercurial darcs opam
opam init
opam config env
opam install num // the library that actually want to install
# * install conf-m4
# * install ocamlfind
# * install num
# ==>> failure with ocamlfind : "Unbound module Toploop" =(
# second try
yaourt -S ocaml-findlib
# ==>> it works ! =)
opam install num
# * install ocamlfind
# * install num
# ==>> it works ! =)
```

**Comment by lotusroot13** [comment] 2018-03-30 07:18
Same issue here on arch, have to pacman install `ocaml-findlib` first

**Comment by mor1** [comment] 2018-07-13 11:44
Same on alpine 3.8.0 (at least). 
Either need `apk add ocaml-compiler-libs` or to build a local switch of 4.06.1 (the version of the system compiler) for `opam install -y ocamlfind` to succeed.

**Comment by outkine** [comment] 2018-07-22 11:19
@lotusroot13's solution worked for me.

**Comment by mseri** [comment] 2018-07-22 19:34
I think ich you want ti do this with the system package you need to have both ocaml and ocaml-compiler-libs installed.

It should work seamlessly using an opam installed compiler instead of the system one though

**Comment by erkin** [comment] 2018-08-12 16:29
`opam` package depends on `ocaml` on Arch, so you'll have the system compiler either way. But installing `ocaml-compiler-libs` seems to alleviate this problem.
Installing `ocaml-findlib` isn't necessary and it only works because it pulls `ocaml-compiler-libs` as a dependency.

**Comment by XVilka** [comment] 2019-03-22 07:19
Reproduced on Alpine edge with OCaml 4.07.1 and ocamlfind-1.8.0

**Comment by mseri** [comment] 2019-03-22 09:37
I think we can close this, and add a pointer to the discussion here for the list of solutions: https://discuss.ocaml.org/t/is-there-any-way-to-avoid-error-file-topfind-ml-line-55-characters-12-41-error-unbound-module-toploop/

**Closed by mseri** 2019-03-22 09:37 UTC
