### ISSUE TITLE
coqide and gnome-icon-theme3

### ISSUE THREAD

**Issue by nobrowser** [ocaml/opam-repository#15371] opened 2019-11-23 06:15 UTC
After any `opam update` whatsoever, even after `opam update --development`, `opam upgrade` tells me that package `conf-gnome-icon-theme3` has 
"changed upstream" and, since `coqide` depends on it, I must rebuild `coqide`.  This is getting old, even though there is no error (the rebuild of `coqide` succeeds).

Here is the output of `opam config report`:

```
 matica!115 ~$ opam config report
# opam config report
# opam-version      2.0.4 
# self-upgrade      no
# system            arch=x86_64 os=linux os-distribution=gentoo os-version=2.6
# solver            builtin-mccs+glpk
# install-criteria  -removed,-count[version-lag,request],-count[version-lag,changed],-changed
# upgrade-criteria  -removed,-count[version-lag,solution],-new
# jobs              3
# repositories      2 (http) (default repo at a177b733)
# pinned            2 (git)
# current-switch    default
```

I suspect this is related to:

```
matica!112 ~$ cat !103:$
cat .local/packages/opam/repo/default/packages/conf-gnome-icon-theme3/conf-gnome-icon-theme3.0/opam
opam-version: "2.0"
homepage: "https://github.com/GNOME/adwaita-icon-theme"
bug-reports: "https://gitlab.gnome.org/GNOME/adwaita-icon-theme/issues"
authors: "GNU Project"
license: ["LGPL-3.0-only" "CC-BY-SA-3.0"]
build: []
depexts: [
  ["gnome-icon-theme"] {os-family = "debian"}
  ["gnome-icon-theme"] {os-family = "fedora" | os-family = "rhel"}
  ["gnome-icon-theme"] {os = "macos" & os-distribution = "homebrew"}
  ["gnome-icon-theme"] {os-family = "suse"}
  ["gnome-icon-theme"] {os-distribution = "arch"}
  ["gnome-icon-theme"] {os-distribution = "alpine"}
  ["gnome-icon-theme"] {os-distribution = "nixos"}
  ["gnome-icon-theme"] {os-distribution = "ol"}
]
synopsis: "Virtual package relying on gnome-icon-theme"
description:
  "This package can only install if the gnome-icon-theme package is installed on the system."
flags: conf
```

Note the total absence of gentoo in the above.

Gentoo includes the following two packages.  I have neither of these installed and I never noticed any problems that I could attribute to that fact, including no problems with `coqide`.

```
 matica!117 x11-themes$ ls -d gnome-icon-theme*
gnome-icon-theme-extras  gnome-icon-theme-symbolic
```

**Comment by nobrowser** [comment] 2019-11-23 17:02
Oh, I do have the following installed:

```
x11-themes/gnome-themes-standard
x11-themes/adwaita-icon-theme
```

**Comment by Blaisorblade** [comment] 2019-11-29 14:36
I've tried that on Mac and not Gentoo, but CoqIDE without `gnome-icon-theme`/`adwaita-icon-theme` doesn't find the icons for its toolbar. `gnome-icon-theme` is an alias to `adwaita-icon-theme`, tho I guess the former name is more stable. I'd ask you to try out, but I expect gnome to break without its icons.

@nobrowser Sounds like somebody should add to that file something like
```
  ["adwaita-icon-theme"] {os-distribution = "gentoo"}
```
or maybe with `x11-themes/adwaita-icon-theme` in place of `adwaita-icon-theme`. Would you be willing to send a PR?

You can try that locally using the `opam pin` command; for instance you `opam pin edit conf-gnome-icon-theme3`, modify your copy yourself, and check if that solves your issue.

**Comment by Blaisorblade** [comment] 2019-11-29 14:40
PS: I don't know enough about `opam` to confirm your theory but it sounds plausible; I did create `conf-gnome-icon-theme3` to make `coqide` work correctly (and PR coqide 8.10.0 packages).
I'm sorry I forgot Gentoo, but please do keep in mind I'm just a volunteer.

**Comment by nobrowser** [comment] 2019-11-29 19:58
@Blaisorblade of course, I'm not complaining :-)  Already `opam` as it is bests all the other language specific ecosystems I know (perl,  python etc).  I'll try your suggestion ASAP.

Notes -

1. I  disable the `coqide` toolbar anyway, it is just a waste of space from my POV, so I wouldn't notice a difference.

2. I don't run gnome, so again I am not a good test case.

**Comment by Blaisorblade** [comment] 2019-11-29 20:04
@nobrowser I don't run Gnome either and I can observe the bug — so you might be able to reproduce the actual issue by removing the icons (and enabling the toolbar); but it doesn't matter, especially if the fix works.

> I disable the coqide toolbar anyway, it is just a waste of space from my POV, so I wouldn't notice a difference.

I see — maybe the dependency could be made optional but I don't know how (and it doesn't seem worth it, to me — if somebody cares and can submit a PR, sure).

**Comment by cogumbreiro** [comment] 2019-12-01 18:16
Hi, everyone. Just wanted to let you know this bug is also affecting Ubuntu 19.10. I can try out some commands if you need me to triage the bug in my system.

**Comment by nobrowser** [comment] 2019-12-05 02:53
I applied the workaround suggested by @Blaisorblade and I'm contented for now :-)

**Comment by Blaisorblade** [comment] 2019-12-08 20:29
@cogumbreiro No idea there, because ubuntu is covered through debian, and `gnome-icon-theme` exists on your distro (https://packages.ubuntu.com/eoan/gnome-icon-theme)... Just to double-check: have you rebuilt the package as opam asks?

If yes, I'd suggest you open a new issue, as I suppose the root cause must be different? But no real idea.

**Comment by cogumbreiro** [comment] 2019-12-08 21:43
@Blaisorblade, What do you mean by "rebuilding package `gnome-icon-theme3` as opam asks?" I don't see opam asking me to do anything, nor explaining how to achieve that step. The only output I get from opam is listed below. 

```
$ opam upgrade
The following actions will be performed:
  ↻ recompile conf-gnome-icon-theme3 0      [upstream changes]
  ↻ recompile coqide                 8.10.2 [uses conf-gnome-icon-theme3]
===== ↻ 2 =====
Do you want to continue? [Y/n] 
```

**Comment by Blaisorblade** [comment] 2019-12-08 22:42
@cogumbreiro Well, that's what I meant — you should say yes. Then opam will recompile those packages, that is, *rebuild* them. After that, if you run `opam date` and `opam upgrade` again, it usually should not ask that question again — unless there are "upstream changes" — that is, the package definition of `conf-gnome-icon-theme3` got modified by opam maintainers (as it will be when #15486 gets merged).

The only bug is if opam asks that question even without actual such upstream changes.

**Comment by cogumbreiro** [comment] 2019-12-09 15:43
@Blaisorblade sorry for not being clear in my previous post. Yes, that opam asks to recompile without actual upstream changes.

After answering yes in the above prompt if I do `opam update` followed by `opam upgrade`, or if I just run `opam upgrade`, I get the same prompt again.

**Comment by Blaisorblade** [comment] 2019-12-09 16:55
@cogumbreiro No worries. Turns out I have the same issue now *in one of my switches*. Still no clue, except that it might be a duplicate of https://github.com/ocaml/opam/issues/3995?

**Comment by Blaisorblade** [comment] 2019-12-09 17:36
Ok, now that I can reproduce it, I have a moderately sensible hypothesis.

@cogumbreiro Can you run `opam pin edit conf-gnome-icon-theme3` and save the result without changes? On my machine, that's a sufficient workaround, and that might be what helped @nobrowser.

My main switch didn't suffer from this, because I had done that already at some point.

**Comment by rjbou** [comment] 2019-12-09 19:35
It's because of opam file parsing/printing. On parsing, the non empty `build:` field is transformed as `[ [] ]`, but on printing, this case is handled and as the field is empty, disappears. As `[] <> [[]]`, opam considers that repo opam file and the installed opam file are not equal, so marks it as an upstream change occurs.

**Comment by Blaisorblade** [comment] 2019-12-09 21:20
@rjbou That's what I feared. Couldn't opam transform both files the same way?

**Closed** 2019-12-09 21:26 UTC
