### ISSUE TITLE
gsl fails to install since recently

### ISSUE THREAD

**Issue by glondu** [ocaml/opam-repository#24308] opened 2023-08-24 07:47 UTC
Since recently, gsl, hence orpie, fails to install in a 4.13.1 switch:
```
[ERROR] The compilation of gsl.1.24.3 failed at "dune build -p gsl -j 1".

#=== ERROR while compiling gsl.1.24.3 =========================================#
# context     2.1.2 | linux/x86_64 | ocaml-base-compiler.4.13.1 | https://opam.ocaml.org#1da29ec1
# path        ~/.opam/4.13.1/.opam-switch/build/gsl.1.24.3
# command     ~/.opam/4.13.1/bin/dune build -p gsl -j 1
# exit-code   1
# env-file    ~/.opam/log/gsl-2228388-3a2392.env
# output-file ~/.opam/log/gsl-2228388-3a2392.out
### output ###
# File "src/dune", line 78, characters 0-101:
# 78 | (rule
# 79 |   (targets sf.mli sf.ml)
# 80 |   (deps config/do_sf.exe sf.mli.q)
# 81 |   (action (run config/do_sf.exe))
# 82 | )
# (cd _build/default/src && config/do_sf.exe)
# Fatal error: exception Sys_error("gsl_include.sexp: No such file or directory")
```

As far as I can tell, it wasn't the case on 2023-08-21. I haven't seen any other suspicious upgrade since then... However, biniou did downgrade from 1.2.2 to 1.2.1 in my switch.

Context: https://salsa.debian.org/ocaml-team/opam-debian-switch

**Comment by kit-ty-kate** [comment] 2023-08-29 16:16
Mmh, I can't reproduce it locally and it was supposed to be fixed by https://github.com/ocaml/opam-repository/pull/19244
Is this deterministically reproducible with your setup?

**Comment by glondu** [comment] 2023-08-30 09:04
It is strange. It seems deterministically reproducible when I (try to) install all [these packages](https://salsa.debian.org/ocaml-team/opam-debian-switch/-/blob/master/opams-to-install.txt) (except ppx_globalize) at once in an empty 4.13.1 switch. However, installing orpie alone in an empty switch, or installing it after all the others are installed, succeds.

**Comment by kit-ty-kate** [comment] 2023-09-04 19:20
I've tried to reproduce locally with all those packages at once but it worked for me

**Comment by glondu** [comment] 2023-09-05 06:41
I just remembered that I [applied a patch](https://salsa.debian.org/ocaml-team/ocamlgsl/-/blob/master/debian/patches/0001-Add-gsl_include.sexp-to-deps-of-sf.ml.patch) in Debian. A similar fix was [applied upstream](https://github.com/mmottl/gsl-ocaml/commit/0b38a22d9813de27eab5caafafeabd945f298b5e), but not released yet. A kind of race condition does exist in the package in its current form. Maybe the patch should be applied in the opam package as well?

**Comment by kit-ty-kate** [comment] 2023-09-05 12:41
I was under the impression that `dune build -j1` (from https://github.com/ocaml/opam-repository/pull/19244) would be an alternative fix for this. Does `-j` not make the build order deterministic in dune? cc dune devs @rgrinberg @emillon @Leonidas-from-XIV @gridbugs

**Comment by kit-ty-kate** [comment] 2023-09-05 13:11
> This has probably changed several times between dune versions.

ah, I see. Very unfortunate. Thanks a lot!

@glondu could you open a PR to add your patch to the relevant versions? (and maybe restore `"-j" jobs` at the same time)
@mmottl could you do a release when you have some spare time?

**Comment by emillon** [comment] 2023-09-05 13:13
I mean, on the other side I can't tell you for sure it has changed, but the build engine has changed enough that I'd say this kind of thing is likely to have changed.

**Comment by rgrinberg** [comment] 2023-09-05 13:14
With the introduction of background threads, not even `-j 1` guarantees a deterministic order of actions. There's some environment variables to disable the various background threads if this desirable.

**Closed** 2023-09-05 15:47 UTC
