### ISSUE TITLE
Many packages fail to install with ocamlbuild.0.9.1 in Cygwin OPAM + MinGW OCaml

### ISSUE THREAD

**Issue by camlspotter** [ocaml/opam-repository#6224] opened 2016-04-12 07:55 UTC
Many packages fail to install due to new hygine violation errors under `_build` directory with ocamlbuild.0.9.1.  I use Cygwin OPAM + MinGW OCaml, so my system is a bit wierd, but it seems to be true for all the OSes.

**Comment by dbuenzli** [comment] 2016-04-12 08:05
Could you report the package names please.

**Comment by camlspotter** [comment] 2016-04-13 02:06
I have checked that Ubuntu has no issue.  It seems MinGW specific...

**Comment by camlspotter** [comment] 2016-04-13 07:51
Found.  It is a bug of ocamlbuild.0.9.1.  The code round line 150 of src/main.ml defines how to exclude files and directories from the hygiene checks, but this is modified between 0.9.0 and 0.9.1.

In 0.9.0, `_build` was simply excluded at the first test of `name.[0] <> '_'`.  In 0.9.1, this is changed: in Linux, `_build` is checked against `` `pwd`/_build`` at the last check with path normalizations, in MinGW, the path normalization does not return the same full path from `` `pwd`/_build`, since the path concatenation is done by `/`, not `\`.

**Comment by gasche** [comment] 2016-06-02 11:02
I included a fix for this issue in 0.9.2, could you confirm that the issue is solved?

(There remain some Windows-specific issues which will hopefully be fixed in the next release.)

**Comment by gasche** [comment] 2016-10-12 15:09
@camlspotter, do I understand correctly that this is was fixed by ocamlbuild 0.9.2, and that the issue can now be closed?

**Comment by camlspotter** [comment] 2016-10-13 09:28
I have reinstalled various OPAM packages in MinGW with ocamlbuild 0.9.2.  It still requires some patches for MinGW, but the part of this issue is fixed.  Please close this ticket, and thanks a lot.

**Comment by dbuenzli** [comment] 2017-07-02 22:49
This can be closed.

**Closed** 2017-07-03 01:57 UTC
Labels: portability
