### ISSUE TITLE
ppx_blob should depend on ppx_tools

### ISSUE THREAD

**Issue by smondet** [ocaml/opam-repository#4043] opened 2015-05-04 20:57 UTC
It doesn't https://github.com/ocaml/opam-repository/blob/master/packages/ppx_blob/ppx_blob.0.1/opam

```
ocamlfind: Package `ppx_tools' not found - required by `ppx_blob'
```

**Comment by johnwhitington** [comment] 2015-05-15 17:59
My last commit is commented "Remove ppx_tools dependency and ...", so it seems it was no longer needed. It installs from source here with OCaml 4.02.1 with no problem, and with OPAM too (without ppx_tools installed):

feast:repos john$ opam install ppx_blob
The following actions will be performed:
  ∗  install ppx_blob 0.1

=-=- Gathering sources =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=  🐫 
[default] https://opam.ocaml.org/archives/ppx_blob.0.1+opam.tar.gz downloaded

=-=- Processing actions -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=  🐫 
∗  installed ppx_blob.0.1
Done.

**Comment by smondet** [comment] 2015-05-15 18:06
The ocamlfind error was when using (not installing) `ppx_blob`.

 (that's also why I didn't do a PR, I'm not sure who's fault it is; or where should this be fixed, `ppx_blob`'s `META` file does not list `ppx_tools` and ocamlfind was still complaining).

**Comment by johnwhitington** [comment] 2015-05-15 18:39
I can confirm this is a problem. If I build the example in the ppx_blob source using the OPAM-installed ppx_blob I get

```
feast:example john$ make
ocamlfind ocamldep quine.ml > ._d/quine.d
ocamlfind ocamlopt -package ppx_blob -c -g -w -3 quine.ml
ocamlfind: Package `ppx_tools' not found - required by `ppx_blob'
make[1]: *** [quine.cmx] Error 2
make: *** [native-code] Error 2
```

However, if I build it from source, and install using "make install", everything is fine:

```
feast:example john$ make
ocamlfind ocamlopt -package ppx_blob -c -g -w -3 quine.ml
ocamlfind ocamlopt \
				-package ppx_blob -linkpkg \
				        -g        -o quine \
				quine.cmx
```

This is odd, because this is exactly what opam install ppx_blob should do...

**Comment by samoht** [comment] 2016-09-28 09:38
Seems to be fixed upstream, so closing.

**Closed by samoht** 2016-09-28 09:38 UTC
