### ISSUE TITLE
libcamlrun.a Error 1

### ISSUE THREAD

**Issue by kid-with-phone** [ocaml/opam-repository#26359] opened 2024-08-15 11:45 UTC
Installation fails:

```
#=== ERROR while compiling ocaml-base-compiler.5.2.0 ==========#
# context     2.2.0 | linux/arm64 |  | https://opam.ocaml.org#47c192ba656a7b302c16bde355fbbe34e0dbf937
# path        ~/.opam/default/.opam-switch/build/ocaml-base-compiler.5.2.0
# command     /data/data/com.termux/files/usr/bin/make -j7
# exit-code   2
# env-file    /data/data/com.termux/files/usr/tmp/opam-xxx-5475/ocaml-base-compiler-5475-0ee6d1.env
# output-file /data/data/com.termux/files/usr/tmp/opam-xxx-5475/ocaml-base-compiler-5475-0ee6d1.out
### output ###
# make[1]: Entering directory '/data/data/com.termux/files/home/.opam/default/.opam-switch/build/ocaml-base-compiler.5.2.0'
# [...]
#   CC runtime/weak.b.o
#   CC runtime/backtrace_byt.b.o
#   CC runtime/fail_byt.b.o
#   CC runtime/fix_code.b.o
#   CC runtime/interp.b.o
#   CC runtime/startup_byt.b.o
#   CC runtime/zstd.b.o
#   MKLIB runtime/libcamlrun.a
# make[1]: *** [Makefile:1315: runtime/libcamlrun.a] Error 1
# make[1]: Leaving directory '/data/data/com.termux/files/home/.opam/default/.opam-switch/build/ocaml-base-compiler.5.2.0'
# make: *** [Makefile:830: world.opt] Error 2
```

```
~ $ opam config report
# opam config report
# opam-version         2.2.0
# self-upgrade         no
# system               arch=arm64 os=linux os-distribution=android os-version=10
# solver               builtin-mccs+glpk
# install-criteria     -removed,-count[avoid-version,changed],-count[version-lag,request],-count[version-lag,changed],-count[missing-depexts,changed],-changed
# upgrade-criteria     -removed,-count[avoid-version,changed],-count[version-lag,solution],-count[missing-depexts,changed],-new
# jobs                 7
# current-switch       none set
~ $
```

**Comment by kid-with-phone** [comment] 2024-08-15 20:18
Sorry for the delay, I didn't get a notification
I pasted the output into a file: 
[opam.txt](https://github.com/user-attachments/files/16629926/opam.txt)

**Comment by kit-ty-kate** [comment] 2024-08-16 10:39
mmh, there doesn't seem to be any relevant error message other than
```
#   MKLIB runtime/libcamlrun.a
# make[1]: *** [Makefile:1315: runtime/libcamlrun.a] Error 1
```
Could you open a ticket in the OCaml issue tracker: https://github.com/ocaml/ocaml/issues
the compiler devs might be able to understand this better than i do

**Comment by MisterDA** [comment] 2024-09-04 09:39
This can be closed, the issue is handled in the compiler.

**Comment by kit-ty-kate** [comment] 2024-09-04 13:46
Will be fixed by https://github.com/ocaml/ocaml/pull/13405

**Closed by kit-ty-kate** 2024-09-04 13:46 UTC
