### ISSUE TITLE
Problem with the installation of tuareg

### ISSUE THREAD

**Issue by james-elliot** [ocaml/opam-repository#19024] opened 2021-07-08 13:03 UTC
When installing tuareg, it complains that emacs-nox is not installed, even when emacs-gtk is installed, which provides the same functionality. Would it be possible to modify the dependency in order to depend on emacs-nox or on emcs-gtk?
Thanks

**Comment by dra27** [comment] 2021-07-08 13:30
Transferred from opam - this affects the depexts specification on `conf-emacs`

**Comment by GoPavel** [comment] 2022-08-09 15:22
I guess the actual issue is #21403

**Comment by kit-ty-kate** [comment] 2022-08-09 16:37
Indeed. Closed as duplicate of https://github.com/ocaml/opam-repository/issues/21403

**Closed by kit-ty-kate** 2022-08-09 16:37 UTC
Labels: persist
