### ISSUE TITLE
ocamlbuild is not available because your system doesn't comply with ocaml-version >= "4.03".

### ISSUE THREAD

**Issue by trefis** [ocaml/opam-repository#5524] opened 2016-01-29 15:30 UTC
@gasche :
```
The following dependencies couldn't be met:
  - lwt -> ocamlbuild
Your request can't be satisfied:
  - ocamlbuild is not available because your system doesn't comply with ocaml-version >= "4.03".
```

My switch is 4.02.3.

**Comment by gasche** [comment] 2016-01-29 15:36
This is rather weird as [ocamlbuild.0](https://github.com/ocaml/opam-repository/blob/master/packages/ocamlbuild/ocamlbuild.0/opam) should be available in your situation. Which dependency solver are you using?

Did you "opam update" recently? When? What actions made the problem appear?

(This *could* be a bug somewhere related to the recent addition of `conflicts: base-ocamlbuild` in `ocamlbuild.0.9.0`: that conflict information could somehow be mistakenly propagated to the `ocamlbuild.0` package.)

**Comment by trefis** [comment] 2016-01-29 15:39
I `opam update`d a few minutes before trying to install a package (and getting that error).
The problem appeared when trying to `opam install` a package (however I'm a bit surprised that the dependency which couldn't be met is "lwt -> ocamlbuild" since lwt is already installed on that switch...).

**Comment by gasche** [comment] 2016-01-29 15:45
It might be the case that you did not update against opam-repository since I added `ocamlbuild` as a new dependency to a bazillion of packages, and `lwt` thus had its dependencies changed. (I hope OPAM would not have rebuilt it after installing ocamlbuild, but if so, too bad.)

**Comment by trefis** [comment] 2016-02-01 13:51
> It might be the case that you did not update against opam-repository since I added ocamlbuild as a new dependency to a bazillion of packages, and lwt thus had its dependencies changed. (I hope OPAM would not have rebuilt it after installing ocamlbuild, but if so, too bad.)

I did update against the official "opam-repository", but I hadn't upgraded. Is that what you meant?

I indeed needed to force the reinstall of lwt for things to proceed normally.

**Comment by gasche** [comment] 2016-02-04 21:32
@trefis I am simultaneously rather worried by this issue report (does that mean that the current ocamlbuild transition is broken for everyone?), unable to do much without more actionable information or a reproducibility description, and unable to actually take time to look at the issue much further in the following days. Could you do something miraculous on your side?

**Comment by vzaliva** [comment] 2016-02-06 00:07
I am having the same issue here under MacOS. Let me know if I can provide any additional information to help to diagnose it.

**Comment by gasche** [comment] 2016-02-06 15:06
I cannot reproduce the issue from a new switch (install `lwt` just works). I am afraid this is a OPAM/solver interaction issue, but I have no clue what could be done to help it. @AltGr , any suggestion?

@trefis , could you describe in a bit more details the way you worked around the problem, so that people having the same issue can use your solution.

**Comment by AltGr** [comment] 2016-02-11 01:10
Situations where the constraints of installed packages are changed and lead to an inconsistent set of packages being installed are difficult to handle. Yet, I have been taking great care to attempt to do it properly. I am a bit short on details to debug here, though, `opam config report`, dumps of the universe (`opam config cudf-universe`) and  solver info (`--dry-run --debug --cudf <file-prefix>`) would be helpful. Failing that, versions or at least precise dates of the repository before and after update, as well as the set of important installed packages might enable me to reproduce.

Do you have any pinned packages ? Did'nt opam print a warning after update ("universe got broken, please run `opam upgrade --fixup`") ? Did you try `--fixup` ?

Also, what opam is saying in the message above is that it can't find a version of ocamlbuild it can install. Try `opam install ocamlbuild --show` to get more details on this.

Thanks!
Louis

**Comment by vzaliva** [comment] 2016-02-11 01:36
I am not the original reporter but I am also have this problem. I do have 'ocalmbuild' installed (version 0). I tried ``opam upgrade --fixup`` and it did not help. I am attaching output of commands you mentioned. I will be glad to provide any additional information you need to fix this. Thanks!

- [opam-upgrade-debug.txt](https://github.com/ocaml/opam-repository/files/125772/opam-upgrade-debug.txt)
- [opam-cudf-universe.txt](https://github.com/ocaml/opam-repository/files/125771/opam-cudf-universe.txt)
- [opam-config-report.txt](https://github.com/ocaml/opam-repository/files/125770/opam-config-report.txt)

**Comment by AltGr** [comment] 2016-02-11 02:51
Thanks a lot! Running the failing command with `--show --cudf xxx` will output a bunch of files named `xxx-*`. These would also be very helpful. Thanks!

**Comment by vzaliva** [comment] 2016-02-11 02:54
I just did ``opam upgrade --show --cudf xxx``. The files are attached. I have to ZIP them as github did not like the file format.

[xxx.zip](https://github.com/ocaml/opam-repository/files/125817/xxx.zip)

**Comment by AltGr** [comment] 2016-02-11 03:00
Awesome, thanks.

**Comment by AltGr** [comment] 2016-02-11 04:54
@vzaliva sorry to ask you again, what is the exact command that failed ? Thanks.

**Comment by vzaliva** [comment] 2016-02-11 06:01
```
lambda13 ~/tmp$ opam upgrade --verbose
Everything as up-to-date as possible.
The following newer versions couldn't be installed:
  - camlp4.4.03 is not available because your system doesn't comply with ocaml-version >= "4.03".
  - ocamlbuild.0.9.0 is not available because your system doesn't comply with ocaml-version >= "4.03".
The following would require downgrades or uninstalls, but you may upgrade them explicitly:
  - async.113.24.00
  - async_extra.113.24.00
  - async_kernel.113.24.00
  - async_rpc_kernel.113.24.00
  - async_unix.113.24.00
  - bin_prot.113.24.00
  - coq.8.5.0
  - coq-color.1.2.0
  - coq-ext-lib.1.0.0~beta2
  - core.113.24.00
  - core_extended.113.24.00
  - core_kernel.113.24.00
  - email_message.113.24.00
  - fieldslib.113.24.00
  - re2.113.24.00
  - sexplib.113.24.00
  - textutils.113.24.00
  - typerep.113.24.00
  - variantslib.113.24.00
```

**Comment by AltGr** [comment] 2016-02-11 06:58
Ah! I believe this is different from @trefis's issue, and in your case, there is actually nothing to worry about. Sorry for the noise, should have started there.
Here is a short explanation:

Opam believes that 0.9 is better than 0, so when you ask to upgrade in verbose mode and everything is "as up-to-date as possible", it will show you the packages that it didn't upgrade and why. In this case camlp4 and ocamlbuild are intended to be kept at these versions -- the misleading part is the word "newer", and is due to the way we abuse version numbers.

(there is ongoing work to remove this abuse and makes things clearer by having different packages "provide" a given feature, but it's not quite there yet!)

**Comment by trefis** [comment] 2016-02-11 08:48
Sorry for not answering before... I didn't have time to investigate: I just manually installed ocamlbuild, which worked fine, it caused lwt to be reinstalled and after that I could install my package.

I've been having some more issues with opam recently and I now believe that all my problems come from the fact that I'm using "the shitty solver"™
Which seem to be coherent with the fact that noone else is encountering that issue.

**Comment by AltGr** [comment] 2016-02-11 10:11
Shouldn't have triggered a rebuild if the dependency was correctly tagged as  `{build}`.
Other than that... yeah, you should use a solver, still nothing embedded but we now have [several options](http://opam.ocaml.org/doc/Install.html#ExternalSolvers).
This said I appreciate to have someone reliable around to test the embedded solver a little ;)

**Comment by vzaliva** [comment] 2016-02-11 16:34
@AltGr Would that issue prevent any future updates of the packages depending (even indirectly) on ocamlbuild?

**Comment by gasche** [comment] 2016-02-11 16:46
(Of course if that were the case (I hope not) I would revert the ocamlbuild-dependencies change to the OPAM metadata.)

**Comment by AltGr** [comment] 2016-02-16 00:39
@vzaliva, in your case, absolutely not -- unless they specifically depend on `ocamlbuild >= "0.9"`, but no package does that. In the original bug neither, but there, I haven't figured out the issue exaclty yet, so I can just say "I don't see how that would happen", without certainty that there is not.

**Comment by samoht** [comment] 2016-09-28 09:15
I am closing that issue, please re-open if you see that error popping up again.

**Closed by samoht** 2016-09-28 09:15 UTC

**Comment by Tizioincognit0** [comment] 2018-06-09 10:48
I have the same error installing a package named “usbmux”.

opam install usbmux
The following dependencies couldn't be met:
  - usbmux -> lwt < 3.0.0
Your request can't be satisfied:
  - lwt<3.0.0 is not available because your system doesn't comply with ocaml-version >= "4.02.0" & compiler != "4.02.1+BER" & ocaml-version < "4.06.0".
