### ISSUE TITLE
How to run "X+musl+static+flambda" on Debian?

### ISSUE THREAD

**Issue by vog** [ocaml/opam-repository#12769] opened 2018-10-09 08:23 UTC
I'd like to use the following OCaml variant on Debian:

"ocaml-variants.4.07.1+musl+static+flambda"

This needs `musl-clang`, and the documentation says that I need to install `musl-tools` on Debian. However, Debian's `musl-tools` contains only a GCC wrapper (`musl-gcc`), not a Clang wrapper. Also, I can't find any other Debian package providing `musl-clang`.

So two questions arise:

* Is that variant supposed to run on Debian at all?
* Are there technical reasons why it requires Clang instead of GCC?

**Comment by nojb** [comment] 2018-10-09 08:52
> Are there technical reasons why it requires Clang instead of GCC?

I would be surprised if there were, since OCaml is compiled with `gcc` in most Unix platforms.

Have you tried replacing `musl-clang` by `musl-gcc` in the `opam` recipe ?

**Comment by rjbou** [comment] 2018-10-09 10:00
@nojb @vog, yes it is the good command to edit a package to pin. opam will store the new definition in its internal folder (`<opamroot>/<opamswitch>/.opamtswitch/overlay/<package>/opam` and uses it for all operation (in this switch). To update it, just re-use this command.

**Comment by tuncer** [comment] 2018-10-09 22:01
Fixed in #12772. You're right that for portability across Linux distros it's better to prefer `musl-gcc`, where it's more likely that `cc` is `gcc`. In fact, I didn't have a strong argument/reason to prefer `clang` when creating the recipe anyway, so let's change it.

Be aware that the compiler variant could not, last time I tried, be used to create fully static binaries of OCaml programs. That's the goal, though, and from what I understand, it's possible and might just require adjusting compiler defaults in the toolchain. Hence, improvements are very welcome.

**Closed as completed** 2018-10-10 06:00 UTC

**Comment by vog** [comment] 2018-10-10 08:14
Thanks! How can I test this?

I just recreated an fresh OPAM root using the same command as before:

    opam init -c 4.07.1+musl+static+flambda ...

However, it still tries to use `musl-clang`. Output:

```
# Configuring OCaml version 4.07.1
# Configuring for host x86_64-unknown-linux-gnu ...
# Configuring for target x86_64-unknown-linux-gnu ...
# Using compiler musl-clang -Os.
# ./configure: 1: ./configure: musl-clang: not found
...
┌─ The following actions failed
│ λ build ocaml-variants 4.07.1+musl+static+flambda
```

What do I need to do to use the updated recipe?

**Comment by nojb** [comment] 2018-10-10 08:39
I think you should first call `opam update` to get the up-to-date package definitions.

**Comment by vog** [comment] 2018-10-10 09:41
Indeed, I'm using "opam init". Is there any other kind of cache that I need to clear? Or, do I need to wait some time until that change is fully deployed to the opam repository?

**Comment by vog** [comment] 2018-10-10 13:33
Okay, obviously this change just didn't make it to the OPAM repository yet:

* https://opam.ocaml.org/packages/ocaml-variants/ocaml-variants.4.07.1+musl+static+flambda/

> "Official 4.07.1 release compiled with **musl-clang** -static and with flambda activated"

So I assume I just need to wait a day, or so.

**Comment by vog** [comment] 2018-10-11 10:12
Meanwhile, the day is over, but the new gcc-based variant stil isn't online.

What do I need to do to use it?

**Comment by pmetzger** [comment] 2018-10-11 11:04
Generally, you might find that you have more luck asking questions like this of a broader audience (say on discuss.ocaml.org.)

**Comment by vog** [comment] 2018-10-11 20:06
Meanwhile, OPAM is updated, so I tried again:

    opam init -c 4.07.1+musl+static+flambda ...

Unfortunately, the build now fails (on Debian) with a different error message:

```
#=== ERROR while compiling ocaml.4.07.1 =======================================#
# context     2.0.0 | linux/x86_64 | ocaml-variants.4.07.1+musl+static+flambda | https://opam.ocaml.org#ebd2104d
# path        /.../opamroot/4.07.1+musl+static+flambda/.opam-switch/build/ocaml.4.07.1
# command     /...opamroot/opam-init/hooks/sandbox.sh build ocaml unix.cma gen_ocaml_config.ml
# exit-code   2
# env-file    /tmp/.../ocaml-5752-0325cb.env
# output-file /tmp/.../ocaml-5752-0325cb.out
### output ###
# Cannot load required shared library dllunix.
# Reason: dllunix.so: dynamic loading not supported on this platform.
```

@tuncer Did this work for you? If so, which system (Linux distro) are you using?

**Comment by tuncer** [comment] 2018-10-15 13:34
The `musl-clang` used to work, and I can confirm the build error with `musl-gcc`. We pass `"-no-shared-libs"`, but maybe that isn't enough with 4.07.1. I'm unaware of other configure flags. @nojb?

**Comment by nojb** [comment] 2018-10-15 13:36
Looks like `opam 2` sandbox scripts require dynamic loading. It is not an error with the compiler itself.

**Comment by nojb** [comment] 2018-10-15 13:39
Can you try by re-initing your `opam` installation with `opam init --disable-sandboxing` ?

**Comment by vog** [comment] 2018-10-15 14:11
That fails with the same error message. Command:

    opam init -n --no-opamrc --disable-sandboxing -c 4.07.1+musl+static+flambda

Result:

```
[NOTE] Will configure from built-in defaults.
Checking for available remotes: rsync and local, git, mercurial, darcs. Perfect!

<><> Fetching repository information ><><><><><><><><><><><><><><><><><><><><><>
[default] Initialised

<><> Creating initial switch (ocaml-variants.4.07.1+musl+static+flambda) ><><><>

<><> Gathering sources ><><><><><><><><><><><><><><><><><><><><><><><><><><><><>
[ocaml-variants.4.07.1+musl+static+flambda] downloaded from cache at https://opam.ocaml.org/cache

<><> Processing actions <><><><><><><><><><><><><><><><><><><><><><><><><><><><>
∗ installed base-bigarray.base
∗ installed base-threads.base
∗ installed base-unix.base
∗ installed ocaml-variants.4.07.1+musl+static+flambda
[ERROR] The compilation of ocaml failed at "/.../4.07.1+musl+static+flambda/bin/ocaml unix.cma
        gen_ocaml_config.ml".

#=== ERROR while compiling ocaml.4.07.1 =======================================#
# context     2.0.0 | linux/x86_64 | ocaml-variants.4.07.1+musl+static+flambda | https://opam.ocaml.org#aaa9f77d
# path        /.../4.07.1+musl+static+flambda/.opam-switch/build/ocaml.4.07.1
# command     /.../4.07.1+musl+static+flambda/bin/ocaml unix.cma gen_ocaml_config.ml
# exit-code   2
# env-file    /tmp/opam-.../ocaml-....env
# output-file /tmp/opam-.../ocaml-....out
### output ###
# Cannot load required shared library dllunix.
# Reason: dllunix.so: dynamic loading not supported on this platform.



<><> Error report <><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><>
┌─ The following actions failed
│ λ build ocaml 4.07.1
└─ 
┌─ The following changes have been performed
│ ∗ install base-bigarray  base
│ ∗ install base-threads   base
│ ∗ install base-unix      base
│ ∗ install ocaml-variants 4.07.1+musl+static+flambda
└─ 
# Run eval $(opam env) to update the current shell environment
Switch initialisation failed: clean up? ('n' will leave the switch partially installed) [Y/n] Y
```

**Comment by nojb** [comment] 2018-10-15 14:29
It seems `opam` 2 requires shared libs as part of its normal operations. Definitely a bug. Will have to fix this upstream I think.

**Comment by nojb** [comment] 2018-10-15 14:33
Reported the bug upstream.
