### ISSUE TITLE
Failed to install protobuf

### ISSUE THREAD

**Issue by smartdabao** [ocaml/opam-repository#15979] opened 2020-03-11 08:14 UTC
I could not install protobuf with 4.09.0, I also tried 4.07.0 or other versions. Error messages are as follows when I use command: opam install protobuf. 

> The following dependencies couldn't be met:
>   - protobuf → core < 111.17.00 → ocaml < 4.03
>       base of this switch (use `--unlock-base' to force)

if I use --unlock-base option, error meesages are as follows.

> [ERROR] Sorry, resolution of the request timed out.
>         Try to specify a simpler request, use a different solver, or increase the allowed time by setting OPAMSOLVERTIMEOUT to a bigger value  (currently, it is set to 60.0 seconds).

I tried to set OPAMSOLVERTIMEOUT to 3600, but it got the same issue.
I have already install core and bitstring package.

> [NOTE] Package core is already installed (current version is v0.13.0).
> [NOTE] Package bitstring is already installed (current version is 3.1.1).

**Comment by XVilka** [comment] 2020-03-16 04:27
It's just seems that the library was abandoned. Of course it cannot compile with the modern OCaml versions and libraries. I recommend to take a look to the [ocaml-protoc](https://github.com/mransan/ocaml-protoc) instead, which I am using myself.

**Comment by avsm** [comment] 2020-04-28 19:30
There is also https://github.com/yallop/ocaml-pb. I'll close this issue, as it's not a bug in opam-repository. Good luck with your protobuf explorations! You may find discuss.ocaml.org a useful place to ask for more advice on the ecosystem.

**Closed by avsm** 2020-04-28 19:30 UTC
