### ISSUE TITLE
conf-dbm triggers false "upstream changes"

### ISSUE THREAD

**Issue by MdeLv** [ocaml/opam-repository#16308] opened 2020-04-28 16:02 UTC
I have the same non blocking and endless behavior each time I do `opam update && opam upgrade`.

>   ↻ recompile conf-dbm                      1.0.0          [**upstream changes**].

This uselessly triggers a recompilation proposal conf-dbm and of all dependent packages.
In [conf-dbm.1.0.0/opam](https://github.com/ocaml/opam-repository/blob/master/packages/conf-dbm/conf-dbm.1.0.0/opam) the field _build_ indicates that is just a shell command (no archive download):
```
build: [
  "sh" "-c" "cc test_gdbm.c -I/usr/include  ... ||
             cc test_gdbm.c    ...```
```
and opam logs says:
```
(very long opam shell command : sandbox.sh "build" "sh" "-c" from opam field "build")
(CWD=~/.opam/4.07.1/.opam-switch/build/conf-dbm.1.0.0)
- /usr/bin/ld: /tmp/ccm6OEvR.o: in function `main':
- test_gdbm.c:(.text+0x25): undefined reference to `gdbm_open'
- /usr/bin/ld: test_gdbm.c:(.text+0x35): undefined reference to `gdbm_close'
- collect2: error: ld returned 1 exit status
- /usr/bin/ld: cannot find -lndbm
- collect2: error: ld returned 1 exit status
- /usr/bin/ld: cannot find -ldb1
- collect2: error: ld returned 1 exit status
λ compiled  conf-dbm.1.0.0
```
```
$ cat ~/.opam/4.07.1/.opam-switch/build/conf-dbm.1.0.0
a.out  test_gdbm.c  test_ndbm.c
```
```
$ cat test_gdbm.c
#include <gdbm.h>

int main() {
  GDBM_FILE db = gdbm_open("conf-dbm-testdb", 512, GDBM_WRCREAT, 0600, 0);
  gdbm_close (db);
  return 0;
}

```
That seems to mean that _conf-dbm-testdb_ is absent for /usr/bin/ld .
However, there is a message "λ compiled  conf-dbm.1.0.0" (maybe compiled but not linked?).

(PS: conf-dbm and dbm depext are installed: libgdbm-dev and m4 packages).

**Can you explain how to fix that C stuff? Where does conf-dbm-testdb come from?
This may also solve the trouble caused to opam, triggered with a false "upstream change" event**

PS: someone already mentioned there but the issue is _stale_ [ conf-dbm #13775 ](https://github.com/ocaml/opam-repository/issues/13775)

**Comment by kit-ty-kate** [comment] 2020-04-28 16:21
What distribution/system are you running?

**Comment by MdeLv** [comment] 2020-04-28 16:26
debian buster.

**Comment by kit-ty-kate** [comment] 2020-04-28 17:22
Testing this in docker seems to work:
```
$ docker run --rm -it ocurrent/opam:debian-10 opam depext -ui conf-dbm
# Detecting depexts using vars: arch=x86_64, os=linux, os-distribution=debian, os-family=debian
# The following system packages are needed:
libgdbm-dev
The following command needs to be run through "sudo":
    apt-get update
Hit:1 http://deb.debian.org/debian buster InRelease
Get:2 http://deb.debian.org/debian buster-updates InRelease [49.3 kB]
Get:3 http://security.debian.org/debian-security buster/updates InRelease [65.4 kB]
Get:4 http://security.debian.org/debian-security buster/updates/main amd64 Packages [189 kB]
Fetched 304 kB in 1s (324 kB/s)
Reading package lists... Done
# OS package update successful
The following command needs to be run through "sudo":
    apt-get install -qq -yy libgdbm-dev
debconf: delaying package configuration, since apt-utils is not installed
Selecting previously unselected package libgdbm-dev:amd64.
(Reading database ... 17379 files and directories currently installed.)
Preparing to unpack .../libgdbm-dev_1.18.1-4_amd64.deb ...
Unpacking libgdbm-dev:amd64 (1.18.1-4) ...
Setting up libgdbm-dev:amd64 (1.18.1-4) ...
# OS packages installation successful
# Now letting OPAM install the packages
The following actions will be performed:
  - install conf-dbm 1.0.0

<><> Gathering sources ><><><><><><><><><><><><><><><><><><><><><><><><><><><><>

<><> Processing actions <><><><><><><><><><><><><><><><><><><><><><><><><><><><>
-> installed conf-dbm.1.0.0
Done.
# Run eval $(opam env) to update the current shell environment
```
I'm guessing `libgdbm-dev` has been removed from your system some time before you did the last opam update?

When a conf package fails to install in opam, the following line usually appears at the end:
```
The packages you requested declare the following system dependencies. Please make sure they are installed before retrying:
    libgdbm-dev
```

**Comment by MdeLv** [comment] 2020-04-28 19:31
The package libgdbm-dev is not requested when doing `opam upgrade` or `opam install`. It has been present on my system for some years.
I believe this conf-dbm message appeared approx. during 2019.  In 2017-18, I didn't get it. While it's non blocking, I didn't try to fix it.
FYI, I have exactly the same situation with two debian buster machines.

Can you show me the log of `opam install conf-dbm -v`, so we can see how your machine handles this  `conf-dbm-testdb` file?
Thanks.

**Comment by kit-ty-kate** [comment] 2020-04-28 19:59
oh wait, I didn't see that your first message:
```
λ compiled  conf-dbm.1.0.0
```
This means your system did succeed to install this package. `[upstream changes]` simply means the way of testing this packages changed so it has be checked again. This package changed a bit last year (see https://github.com/ocaml/opam-repository/commits/master/packages/conf-dbm) but nothing since. If you are saying that you are experiencing rebuilds of this package everytime for several `opam update -u` consecutively, then it it more likely an issue with opam, not with opam-repository. What version of opam are you using? If it does happen with opam 2.0.7 then it would be better to move this issue in the opam issue-tracker: https://github.com/ocaml/opam/issues/

side note: The rest of the "errors" (which appears only when using `--verbose/-v`) can be discarded. The `conf-dbm-testdb` is simply created by a test to see if everything works correctly. According to the line from the log above, the test worked. So there is nothing to worry about on our side.

**Comment by MdeLv** [comment] 2020-04-29 01:10
I was using opam 2.0.5 . I just upgraded to 2.0.7 . I get the same behavior with conf-dbm installation.
Do you have exactly the same logs (with --verbose) as I published? Can you show them?

> `[upstream changes]` simply means the way of testing this packages changed so it has be checked again.

What do you mean exactly with "the way of testing this package"?
I don't understand what triggers that [upstream changes].

**Comment by dra27** [comment] 2020-04-29 06:53
This is the same issue as https://github.com/ocaml/opam-repository/pull/14912 - the enormous command in conf-dbm.1.0.0 is broken over multiple lines.

**Comment by MdeLv** [comment] 2020-04-29 11:09
In brief : manually fixed, but the wrong conf-dbm opam file is still downloaded by opam/opam-repository when doing `opam install conf-dbm` or `opam reinstall conf-dbm`(tested on two debian machines).

As of today, the [conf-dbm.1.0.0 opam file](https://github.com/ocaml/opam-repository/blob/master/packages/conf-dbm/conf-dbm.1.0.0/opam) has no triple quotes:
```
build: [
  "sh" "-c" "cc test_gdbm.c -I/usr/include -I/usr/local/include ... ||
```             
while the opam file on my machine(s), automatically downloaded by opam, has the triple quotes:
```
build: [
  "sh"
  "-c"
  """
cc test_gdbm.c -I/usr/include -I/usr/local/include ... ||
```
**Manually downloading the github version of the opam file solves the issue (in my context).**
Each new `opam update` doesn't affect that new state (ocaml 4.07.1).
I can observe the same behavior with an ocaml 4.10.0 switch (i.e. endless request conf-dbm for building, then no more request). 
I've just created a fresh 4.10.0 switch and did `opam install dbm`. A triple quote opam file is downloaded I can observe exactly the same behavior.
I also have the same test result with another debian machine (ocaml 4.07.1).

Log doesn't tell what opam exactly does.
```
$ opam update --verbose 
<><> Updating package repositories ><><><><><><><><><><><><><><><><><><><><><><>
[default] no changes from https://opam.ocaml.org
```
Can it be a opam cache issue? 
So I did `opam clean`. Then I observed the same faulty behavior.

**Now, the question is:
what is the cause for opam downloading an old opam file and not  [opam-repository/packages/conf-dbm/conf-dbm.1.0.0/opam](https://github.com/ocaml/opam-repository/blob/master/packages/conf-dbm/conf-dbm.1.0.0/opam)  when doing `opam install` or `opam reinstall`?**

**Comment by avsm** [comment] 2020-04-29 11:15
Did you run `opam update` to update your package descriptions?

**Comment by avsm** [comment] 2020-04-29 11:17
Once that's done, look in `~/.opam/default/.opam-switch/sources/<...>` for the opam file, and see if it's been updated from the upstream one.

**Comment by avsm** [comment] 2020-04-29 11:18
You can also look in `~/.opam/repo/default/` to check the package descriptions you have locally.

**Comment by MdeLv** [comment] 2020-04-29 11:29
I do `opam update && opam upgrade` **each time** I want to upgrade a switch, for sanity.

As I mentioned, I confirm that, say, the ~/.opam/4.10.0_test/.opam-switch/packages/opam file installed (or reinstalled) by opam is the one with triple quotes and **not** the [upstream opam file](https://raw.githubusercontent.com/ocaml/opam-repository/1.2/packages/conf-dbm/conf-dbm.1.0.0/opam). 

FYI, as it may be an opam issue, I opened this issue: [https://github.com/ocaml/opam/issues/4162](https://github.com/ocaml/opam/issues/4162)

**Comment by dra27** [comment] 2020-04-29 12:01
I think what’s happening is that you have a single-quoted string with newlines which opam then normalises to triple-quotes and then you hit the known lexer/printer bug with the first newline in a triple-quoted which is causing opam to think the file has changed on each upgrade. You don’t need to do the update inbetween each call to upgrade to see it.

**Comment by MdeLv** [comment] 2020-04-29 12:07
> You can also look in `~/.opam/repo/default/` to check the package descriptions you have locally.

I confirm that `~/.opam/repo/default/packages/conf-dbm/conf-dbm.1.0.0/opam` is the upstream version( without triple quotes).

**Comment by MdeLv** [comment] 2020-05-29 12:33
Hi,
on  a debian 10 machine, with opam 2.0.5, the same trouble suddenly came back yesterday:
```
The following actions will be performed:               
  ↻ recompile conf-dbm        1.0.0  [upstream changes]
  ↻ recompile dbm             1.2    [uses conf-dbm]   

```
However, the opam file has single quotes.
```
$ cat ~/.opam/repo/default/packages/conf-dbm/conf-dbm.1.0.0/opam
...
build: [
  "sh" "-c" "cc test ...
```

I only have the issue on one machine, with ocaml 4.10.0 (and not with 4.04.1 and 4.08.1 opam _switches_).
The issue was supposed to be solved (opam file with single quotes, as well as opam software fixed)
I upgraded from opam 2.0.5 to opam 2.0.7 on this machine and that did not solve the issue.

What are the prerequisites not to get this behavior?
Where should I have a look to fix that?
Thanks.

**Comment by dra27** [comment] 2020-05-29 13:06
2.0.7 doesn't fix this and the issue is that the string contains a newline, it's not related to the use of triple or single quote marks. The fix for it has been merged in opam-file-format.

**Comment by kit-ty-kate** [comment] 2020-05-29 13:26
Sorry it seems I forgot to fix the issue on the opam package. https://github.com/ocaml/opam-repository/pull/16545 should fix it, sorry for that.

**Comment by MdeLv** [comment] 2020-05-29 14:11
I just checked: 
the opam file on the machines where this behavior has disappeared is the **same** version (corrupted) as on the machine where the problem just appeared.
So the cause of that situation (different behaviors with a  same opam file) should be that the state of the local opam repos where the behavior is fixed has been changed when I did some pinning with the fixed opam file. 
Do you agree?

btw, is there a way to see **all** opam actions?
I've just opened an issue where I also ask that question: https://github.com/ocaml/opam/issues/4213

Thanks.

**Closed** 2020-05-29 14:43 UTC

**Comment by MdeLv** [comment] 2020-06-01 20:41
The problem with local opam repositories is fixed (with https://github.com/ocaml/opam-repository/blob/master/packages/conf-dbm/conf-dbm.1.0.0/opam).
Thanks.

However, **without any** further package installation, a bunch of incompatibilities between opam packages immediately appeared (reproduced on two debian10 machines). See https://github.com/ocaml/opam/issues/4213

I don't know if this is related to conf-dbm.
Did you encounter the same situation?
Thanks.
