### ISSUE TITLE
Unable to install ocamlfind

### ISSUE THREAD

**Issue by hgouraud** [ocaml/opam-repository#5880] opened 2016-03-04 15:58 UTC
Opam installed succesfully on a Mac Air, El Capitan (10.11)
Ocaml and camlp5 installed succesfully.
Failed to install ocamlfinf!!!

```
MacAir-H:~ Henri$ opam install ocamlfind
The following actions will be performed:
  ∗  install conf-pkg-config 1.0              [required by conf-ncurses]
  ∗  install conf-ncurses    1                [required by ocamlfind]
  ∗  install ocamlfind       1.6.1
===== ∗  3 =====
Do you want to continue ? [Y/n] y

=-=- Gathering sources =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=  🐫 
[ocamlfind] Archive in cache

=-=- Processing actions -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=  🐫 
[ERROR] The compilation of conf-pkg-config failed at "pkg-config --help".

#=== ERROR while installing conf-pkg-config.1.0 ===============================#
# opam-version 1.2.2
# os           darwin
# command      pkg-config --help
# path         /Users/Henri/ocamlbrew/ocaml-4.02.3/.opam/4.02.1/build/conf-pkg-config.1.0
# compiler     4.02.1
# exit-code    127
# env-file     /Users/Henri/ocamlbrew/ocaml-4.02.3/.opam/4.02.1/build/conf-pkg-config.1.0/conf-pkg-config-79808-7afd23.env
# stdout-file  /Users/Henri/ocamlbrew/ocaml-4.02.3/.opam/4.02.1/build/conf-pkg-config.1.0/conf-pkg-config-79808-7afd23.out
# stderr-file  /Users/Henri/ocamlbrew/ocaml-4.02.3/.opam/4.02.1/build/conf-pkg-config.1.0/conf-pkg-config-79808-7afd23.err



=-=- Error report -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=  🐫 
The following actions were aborted
  ∗  install conf-ncurses 1    
  ∗  install ocamlfind    1.6.1
The following actions failed
  ∗  install conf-pkg-config 1.0
No changes have been performed

=-=- conf-pkg-config.1.0 troobleshooting =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=  🐫 
=> This package relies on external (system) dependencies that may be missing. `opam depext conf-pkg-config.1.0' may help you find the correct installation for your
   system.
MacAir-H:~ Henri$ 
```

Running opam depext shows no dependency missing

Regards
Henri

**Comment by micksulley** [comment] 2016-03-06 11:37
I have the same issue on Raspbian.  opam install conf-m4.1 fails

=-=- conf-m4.1 troobleshooting =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
=> This package relies on external (system) dependencies that may be missing. `opam depext
   conf-m4.1' may help you find the correct installation for your system.

 but

pi@raspberrypi:~/geneweb $ opam depext
# Detecting depexts using flags: arm armv7 linux raspbian
# No extra OS packages requirements found.

**Comment by avsm** [comment] 2016-03-06 11:39
The issue is here is that `raspbian` is not a recognised external OS.  It ought to be mapped onto `debian` for now.

**Comment by pirbo** [comment] 2016-03-07 22:18
Same issue!
I would say that the problem is that the "build" command of cons-ncurses is
```
["pkg-config" "ncurses"] { os != "darwin" & os != "freebsd" & os != "netbsd" & os != "openbsd" }
```
therefore the depend line should be
```
"conf-pkg-config" { os != "darwin" & os != "freebsd" & os != "netbsd" & os != "openbsd" }
```
which is not possible I guess (I don't find the formal description of <package-formula> in opam manual)

Anyway, this is super annoying to have lost ocamlfind and all these reverse dependencies with no possible foldback !!!

**Comment by OCamlPro-Henry** [comment] 2016-03-07 22:44
Well, the constraint in the `depends` is possible and should have been there already... It should be fixed by https://github.com/ocaml/opam-repository/issues/5898.

**Comment by OCamlPro-Henry** [comment] 2016-03-07 22:45
I am surprised this error was not caught by the CI.

**Comment by pirbo** [comment] 2016-03-07 22:50
Thanks very much for reactivity!
Well I've been bitten by that already: travis OS X nodes install their dependencies through homebrew
 and as soon as you've installed something through home-brew, you've got pkg-config :-)

**Comment by OCamlPro-Henry** [comment] 2016-03-07 23:10
Hmm, I might have spoken too fast (or too late in the evening) :-( adding the "os" predicate in `depends` made the dependency ignored on linux too. 

@AltGr what am I missing here ?

**Comment by rathereasy** [comment] 2016-03-27 17:35
I'm on Ubuntu 15.04 and I'm getting the "The compilation of conf-pkg-config.1.0 failed" error

**Comment by jstolarek** [comment] 2016-05-30 15:36
Getting the same error on openSUSE 11.4. I have pkg-config and development versions of ncurses installed.

**Comment by gasche** [comment] 2016-06-01 02:14
It seems that older versions of ncurses use a special-purpose `ncurses5-config` script instead of `pkg-config`. So we could alternatively try that instead of `pkg-config` in the `conf-ncurses` package. I don't have the time to try to implement such a package right now, but if I (or someone else) does it, would you maybe be able to test the result?

**Comment by hgouraud** [comment] 2016-06-01 04:21
Yes, to the best of my ability, which is limited!!

Henri

Envoyé de mon iPhone

**Closed** 2016-06-05 20:19 UTC
