### ISSUE TITLE
Git push 

### ISSUE THREAD

**Issue by jserot** [ocaml/opam-repository#11384] opened 2018-02-10 11:06 UTC
I've followed the instructions described [here](https://opam.ocaml.org/doc/Packaging.html) (section _Publishing by hand_).

But when trying to push the modification to the `opam/opam-repository` directory, i get 

`remote:Permission to ocaml/opam-repository.git denied to <myname>.
fatal: unable to access 'https://github.com/ocaml/opam-repository.git/': The requested URL returned error: 403`

Thanks for your help

I guess i should have to get the rights for pushing to the github repository.
How/where do i request this ?

**Comment by jpdeplaix** [comment] 2018-02-10 16:43
That's totally normal: you are trying to push to a repository that you don't own (or at least that you does not maintain).
I suppose the instructions are not detailed enough for somebody who never opened a PR; there should be at least two more steps after ```Fork https://github.com/ocaml/opam-repository```:
* Something about "adding a remote to your current local git repository" or "cloning the forked repository"
* And something about "pushing to **your** fork (depending on the remote name you used before)"

The website seems to be generated using this file: https://github.com/ocaml/opam/blob/master/doc/pages/Packaging.md
If you find a formulation that suites you please don't hesitate to send a PR to change that. Otherwise I'll try to find something decent before Monday.

**Comment by jserot** [comment] 2018-02-10 18:00
Thanks for the answer

> That's totally normal: you are trying to push to a repository that you don't own (or at least that you do not maintain).

This is what i suspected ;-)

I'm afraid I'm not familiar enough with Github to suggest relevant modifications to the current procedure.

Would using `opam-publish` make things easier ?

Jocelyn

**Comment by jpdeplaix** [comment] 2018-02-12 11:02
> Would using ```opam-publish``` make things easier ?

I never used ```opam-publish``` myself but, yes probably.

**Comment by AltGr** [comment] 2018-02-12 14:28
Thanks for reporting. Indeed, this isn't very clear.

> Would using `opam-publish` make things easier ?

That's the point, yes. The interface of the current version isn't as easy to use as it should be, though. With version 2.0 you'll only have to run `opam publish` and you're done, but it has to wait for opam 2.0 to be released, and the repository migrated to the new format.

**Comment by AltGr** [comment] 2018-02-12 14:29
(note that rewriting these parts of the docs is part of the roadmap for the imminent release)

**Comment by jserot** [comment] 2018-02-12 14:55
Ok, i think i'll wait for the new version. Nothing hurries here.
Thanks for you feedback !

**Comment by jserot** [comment] 2018-04-08 09:15
I've seen messages about beta releases of opam 2.0.
Is it time to have a try (at least to test the new publishing process) ?

**Comment by AltGr** [comment] 2018-04-11 09:08
Yes, opam 2.0 has been in beta, and now RC for a while. I am just now releasing the new version of `opam-publish`, only available for opam 2 users, and that publishes only to the 2.0.0 repository branch.
You might prefer to wait a week or two for the opam 2.0.0-rc2 release, but the current RC is fairly stable already.

**Comment by jserot** [comment] 2018-04-11 14:04
Ok. I'll try (i'm stuck in the process of manually adding a package using the 1.2 "manual" approach).
On the beta5 announce page (opam.ocaml.org/blog/opam-2-0-beta5), it is said, however that : "You may not yet contribute packages in 2.0 format to opam-repository, though.". Does this mean that the new opam-publish procedure fills the "old" 1.2 repository ?

**Comment by AltGr** [comment] 2018-04-11 15:47
That sentence is now half false: you may still not contribute packages in 2.0 format _to the master branch_ of `opam-repository`, however, you may do so to its 2.0.0 branch (using the new opam-publish 2), and they will be visible to other opam 2 users..
So currently:
* push to opam-repository master (v1.2 package defs): packages visible to both opam 1 and opam 2 users (after automatic conversion fo the latter)
* push to opam-repository branch 2.0.0 (v2 package defs): packages visible _only_ to opam 2 users

**Comment by AltGr** [comment] 2018-04-16 16:26
(the `try opam-publish --help` message is indeed misleading, and caused by the fact that `opam2 publish` actually calls `opam-publish`, within a specific opam PATH, transparently. Not sure how to do better since the message comes from cmdliner... maybe by putting some trick into `Argv.(0)` ?)

**Comment by jserot** [comment] 2018-04-17 07:37
Ok, thanks !
When running `opam2 publish` and after entering my Github credentials, i get :
`[ERROR] No SSL or TLS support compiled into Conduit`.

**Comment by AltGr** [comment] 2018-04-17 09:43
Ah, thanks for reporting! I may have forgotten to port https://github.com/ocaml/opam-repository/pull/11781 to the 2.0 version. Just `opam install tls` should fix this.

**Comment by AltGr** [comment] 2018-04-17 09:50
That should be fixed by https://github.com/ocaml/opam-repository/pull/11803

**Comment by jserot** [comment] 2018-04-17 11:07
Still a pb (sorry for the formatting; i did not found how to md a multi-line bloc of code) : 

=-=- Gathering sources =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=  🐫 
[cohttp-lwt-unix.1.0.2] found in cache
[conduit-lwt-unix.1.1.0] found in cache
[cpuid.0.1.1] found in cache
[github-unix.3.1.0] found in cache
[nocrypto.0.5.4] found in cache
[tls.0.9.1] found in cache
[x509.0.6.1] found in cache

=-=- Processing actions -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=  🐫 
[ERROR] The compilation of cpuid failed at "/Users/jserot/.opam2/default/bin/ocaml pkg/pkg.ml build --pinned false --tests false".

#=== ERROR while compiling cpuid.0.1.1 ========================================#
# context      2.0.0~rc | macos/x86_64 | ocaml-system.4.06.0 | https://opam.ocaml.org/2.0#482c4f94
# path         ~/.opam2/default/.opam-switch/build/cpuid.0.1.1
# command      ~/.opam2/default/bin/ocaml pkg/pkg.ml build --pinned false --tests false
# exit-code    1
# env-file     ~/.opam2/log/cpuid-8715-03b1a4.env
# output-file  ~/.opam2/log/cpuid-8715-03b1a4.out
### output ###
# ocamlfind ocamlopt -package unix -package ocamlbuild -linkpkg -package ocb-stubblr myocamlbuild.ml /Users/jserot/.opam2/default/lib/ocamlbuild/ocamlbuild.cmx -o myocamlbuild
# # opam-version    1.2.2
# # os              darwin
# File /Users/jserot/.opam2/default/config/global-config.config does not existFailure: Ocb_stubblr: error running opam.
# pkg.ml: [ERROR] cmd ['ocamlbuild' '-use-ocamlfind' '-classic-display' '-j' '4' '-tag' 'debug'
#      '-build-dir' '_build' '-plugin-tag' 'package(ocb-stubblr)' 'opam'
#      'pkg/META' 'CHANGES.md' 'LICENSE.md' 'README.md' 'src/cpuid.a'
#      'src/cpuid.cmxs' 'src/cpuid.cmxa' 'src/cpuid.cma' 'src/cpuid.cmx'
#      'src/cpuid.cmi' 'src/cpuid.mli' 'src/dllcpuid_stubs.so'
#      'src/libcpuid_stubs.a']: exited with 2



=-=- Error report -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=  🐫 
┌─ The following actions were aborted
│ ∗  install cohttp-lwt-unix  1.0.2
│ ∗  install conduit-lwt-unix 1.1.0
│ ∗  install github-unix      3.1.0
│ ∗  install nocrypto         0.5.4
│ ∗  install tls              0.9.1
│ ∗  install x509             0.6.1
└─ 
┌─ The following actions failed
│ λ  build cpuid 0.1.1
└─ 
╶─ No changes have been performed

**Comment by kit-ty-kate** [comment] 2018-04-17 16:45
Multi-line blocks are defined by enclosing your text inside 3 backticks (`).
I just edited you comment. You can see how it's done more in details in edit mode.

**Comment by jserot** [comment] 2018-04-18 07:42
Thanks for edit and the tip !

**Closed** 2019-09-16 13:08 UTC
