### ISSUE TITLE
"opam install ocamldot" fails with  "No package matches cstruct-lwt."

### ISSUE THREAD

**Issue by tomjridge** [ocaml/opam-repository#9508] opened 2017-06-14 16:56 UTC
"opam install ocamldot" fails with "Your request can't be satisfied:
  - No package matches cstruct-lwt."

But ocamldot doesn't need cstruct-lwt (this seems to be picked up because of mirage-block-unix).

How can I install ocamldot?

Thanks

```

$ tjr_base_env $ opam update 

=-=- Updating package repositories =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
[default] synchronized from https://opam.ocaml.org

=-=- Synchronizing development packages -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
[ocamlfuse] /tmp/l/git/github/ocamlfuse/ already up-to-date
The brute-force exploration algorithm timed-out [357 states, 5s].
You might need to add explicit version constraints to your request to get a better answer.


Updates available for 4.03.0, apply them with 'opam upgrade':
===== ∗  7   ↻  68   ↗  27   ↘  1 =====

# (h:pc1177) (p:/tmp/l/git/github/tjr_base_env) (d:/dev/loop7[/git])  [master !]
$ tjr_base_env $ opam install ocamldot
The following dependencies couldn't be met:
  - mirage-block-unix -> cstruct-lwt
Your request can't be satisfied:
  - No package matches cstruct-lwt.

No solution found, exiting

# (h:pc1177) (p:/tmp/l/git/github/tjr_base_env) (d:/dev/loop7[/git])  [master !]
$ tjr_base_env $ 

```

**Comment by gasche** [comment] 2017-07-02 14:40
@tomjridge may it work better if you used `opam upgrade` first? My guess would be that the solver tries to update some of the out-of-date packages simultaneously with installing the new package, and that this causes the failure.

Are you using an external solver? See `opam config report | grep external-solver` and [Install#External Solvers](http://opam.ocaml.org/doc/Install.html#ExternalSolvers).

**Comment by dbuenzli** [comment] 2017-07-05 08:39
> The brute-force exploration algorithm timed-out

This indeed seem to indicate that the unusable internal solver is being used (I think it should be removed at some point I'm not sure it's able to perform anything meaningful on the current state of the OCaml opam repository).

Sometimes weird switch state can also be solved by `opam upgrade --fixup` but I wouldn't count on it in this case. Do yourself a favor and install an external solver.

In any case this problem has nothing to do with the `ocamldot` package which install fine and doesn't depend on `cstruct-lwt` at all so I'm closing this.

@tomjridge feel free to continue the discussion on this issue if you need more help w.r.t. external solver install or if there's something wrong with our analysis.

**Closed by dbuenzli** 2017-07-05 08:39 UTC
Labels: needs reporter feedback

**Comment by tomjridge** [comment] 2017-07-05 12:45
I wasn't using the external solver, and somehow I didn't realize that this was responsible for the problem. Sorry. Thanks. @dbuenzli Yes, I think the internal solver should be removed, given that it clearly doesn't work.

Thanks all.

**Comment by dbuenzli** [comment] 2017-07-05 12:58
No worries these things can happen.

**Comment by gasche** [comment] 2017-07-05 13:07
The internal solver is something I've been unhappy about for some time. The problem is that the external solvers are not appropriately packaged for all user systems (for example, I use Fedora 25 and, despite some fair amount of cajoling on my part, the packagers of aspcud/gringo for previous Fedora releases have yet to release a package for that version), and the external solver farm is not something one can depend on by default (I don't even know if it is currently running).

**Comment by tomjridge** [comment] 2017-07-05 14:47
Can we package aspcud using ... opam? Is this crazy?

**Comment by gasche** [comment] 2017-07-05 15:14
It would certainly be an improvement over what we have. The cost is to opam-package everything up the depending chain, and those solvers tend to be quite beefy dependency-wise; it's a C++ project with CMake, and I'm afraid there is some Boost usage etc. But it's a good idea.

**Comment by dbuenzli** [comment] 2017-07-05 15:22
I think it's better if don't start packaging non-ocaml things that are available through the system packagers otherwise: 

1. We don't know where to stop 
2. People will start complain they have two installs of the same thing on their machine. 

This could however maybe be done but only for platforms that have underwhelming support for those.

**Comment by gasche** [comment] 2017-07-05 15:30
I think packaging "stuff that is necessary for opam to function correctly" would be a reasonable bounday. But there is also the problem, that I hadn't thought about previously, that currently (opam 1.2) that would mean the binary is only available on some switches and not other. I don't remember whether opam 2.0 brings a switch-agnostic-bin-place of some sort.

**Comment by dbuenzli** [comment] 2017-07-07 15:39
> The internal solver is something I've been unhappy about for some time

I filed a discussion upstream to discuss this https://github.com/ocaml/opam/issues/2989
