### ISSUE TITLE
opam.ocaml.org is not showing updates since 29 april

### ISSUE THREAD

**Issue by gares** [ocaml/opam-repository#16364] opened 2020-05-06 14:58 UTC
I don't know is this is the right place to report this issue, apologies in advance.

Apparently recently updated packages are not visible on the website, and also cannot be downloaded by the opam utility. I've just noticed this by updating my CI to pull elpi 1.11, PR merged a few hours ago.

**Comment by mseri** [comment] 2020-05-06 15:47
Thanks for the notification, this is the right place.

Somebody is working on it, I hope it will all be back to normal soon. We will close the issue once the problem is solved.

**Comment by rjbou** [comment] 2020-05-06 20:02
It's back! Thanks for the report & notification!

**Closed by rjbou** 2020-05-06 20:02 UTC
