### ISSUE TITLE
tiny_json build fails 

### ISSUE THREAD

**Issue by domsj** [ocaml/opam-repository#7888] opened 2016-11-22 09:10 UTC
probably since https://github.com/ocaml/opam-repository/pull/7727 got merged?

see https://travis-ci.org/openvstorage/alba/jobs/177722354

```
#=== ERROR while installing tiny_json.1.1.2 ===================================#
# opam-version         1.2.2
# os                   linux
# command              ocaml setup.ml -build
# path                 /home/jenkins/OPAM/4.03.0/build/tiny_json.1.1.2
# compiler             4.03.0
# exit-code            1
# env-file             /home/jenkins/OPAM/4.03.0/build/tiny_json.1.1.2/tiny_json-61-642d21.env
# stdout-file          /home/jenkins/OPAM/4.03.0/build/tiny_json.1.1.2/tiny_json-61-642d21.out
# stderr-file          /home/jenkins/OPAM/4.03.0/build/tiny_json.1.1.2/tiny_json-61-642d21.err
### stdout ###
# *** omake: reading OMakefiles
### stderr ###
# [...]
# Warning 3: deprecated: String.uncapitalize
# Use String.uncapitalize_ascii instead.
# File "setup.ml", line 4923, characters 31-48:
# Warning 3: deprecated: String.capitalize
# Use String.capitalize_ascii instead.
# *** omake error:
#    File Omake_builtin: line 0, characters 0-0
#    include file Pervasives not found in OMAKEPATH
#       (OMAKEPATH[] = "." : Sequence /home/jenkins/OPAM/4.03.0/lib/omake : Dir)
# E: Failure("Command 'cp OMakeroot.in OMakeroot; PREFIX=/home/jenkins/OPAM/4.03.0 omake' terminated with error code 123")
```

**Comment by domsj** [comment] 2016-11-22 09:21
Fyi pinning omake to version 0.9.8.6-0.rc1 works around the problem, so it's definitely related to the earlier mentioned PR which introduces omake.0.10.1

**Comment by camlspotter** [comment] 2016-11-30 11:21
Confirmed.  All my omake build packages fail due to omake.0.10.1.

**Comment by rgrinberg** [comment] 2016-12-01 15:09
@domsj @camlspotter  the problem should be fixed once you do opam update and reinstall omake. Sorry, I admit that I'm at fault for causing this issue in the first place.

Nevertheless, I did fix it promptly and it seems to be working fine:

```
opam install tiny_json
The following actions will be performed:
  ∗  install omake     0.10.1                 [required by tiny_json]
  ∗  install tiny_json 1.1.2
===== ∗  2 =====
Do you want to continue ? [Y/n] y

=-=- Gathering sources =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
[omake] Archive in cache
[default] https://opam.ocaml.org/archives/tiny_json.1.1.2+opam.tar.gz downloaded

=-=- Processing actions -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
∗  installed omake.0.10.1
∗  installed tiny_json.1.1.2
Done.
```

```
$ utop
#require "tiny_json";;
─( 10:07:18 )─< command 6 
utop # Tiny_json.Json.parse {|{"omake.0.10.1": "works"}|};;
- : Tiny_json.Json.t =
Tiny_json.Json.Object [("omake.0.10.1", Tiny_json.Json.String "works")]
```

Happy to help with whatever issues you may be having and pull omake.0.10.1 as a last resort if I fail.

**Comment by yallop** [comment] 2017-01-20 12:12
Closing, since this is apparently resolved.  Please reopen if the problem reoccurs.

**Closed by yallop** 2017-01-20 12:12 UTC
