### ISSUE TITLE
Package `conf-pkg-config` not working on Alpine when `apk`'s cache is empty.

### ISSUE THREAD

**Issue by mefyl** [ocaml/opam-repository#22094] opened 2022-09-12 12:54 UTC
In this Docker environment:

```Dockerfile
FROM alpine:3.16.2 AS opam-base

RUN apk add --no-cache gcc make musl-dev opam
RUN opam init --compiler="4.12.0" --disable-sandboxing --shell-setup --verbose --yes
```

Attempting to install `conf-pkg-config` fails:

```
/ # opam install conf-pkg-config
[WARNING] Running as root is not recommended
[ERROR] Package conf-pkg-config depends on the unavailable system package 'pkgconf'. You can use `--no-depexts' to attempt installation anyway.
/ # 
```

Note that apk was invoked with `--no-cache`, which is quite usual in Docker images to avoid bloating the size with unnecessary cache files. Updating the `apk` index fixes the issue :

```
/ # apk update
fetch https://dl-cdn.alpinelinux.org/alpine/v3.16/main/x86_64/APKINDEX.tar.gz
fetch https://dl-cdn.alpinelinux.org/alpine/v3.16/community/x86_64/APKINDEX.tar.gz
v3.16.2-153-g348653a9ba [https://dl-cdn.alpinelinux.org/alpine/v3.16/main]
v3.16.2-152-gc6274c3ddd [https://dl-cdn.alpinelinux.org/alpine/v3.16/community]
OK: 17028 distinct packages available
/ # opam install conf-pkg-config
[WARNING] Running as root is not recommended
The following actions will be performed:
  - install conf-pkg-config 2

The following system packages will first need to be installed:
    pkgconf

<><> Handling external dependencies <><><><><><><><><><><><><><><><><><><><><><>
Let opam run your package manager to install the required system packages?
(answer 'n' for other options) [Y/n] y
+ /sbin/apk "add" "-i" "pkgconf"
- The following NEW packages will be installed:
-   pkgconf
- Need to download 43 KiB of packages.
- After this operation, 140 KiB of additional disk space will be used.
- Do you want to continue [Y/n]? 

- (1/1) Installing pkgconf (1.8.0-r1)
- Executing busybox-1.35.0-r17.trigger
- OK: 137 MiB in 42 packages

<><> Processing actions <><><><><><><><><><><><><><><><><><><><><><><><><><><><>
-> installed conf-pkg-config.2
Done.
# Run eval $(opam env) to update the current shell environment
/ # 
```

**Comment by kit-ty-kate** [comment] 2022-09-12 14:19
Duplicate of https://github.com/ocaml/opam/issues/5186

**Closed by kit-ty-kate** 2022-09-12 14:19 UTC
